version: '3.8'

services:
  products:
    build: .
    working_dir: /app/technolife
    command: ["scrapy", "crawl", "technolifeProduct"]
    env_file:
      - /opt/blackeveryday/config/.env.common
      - /opt/blackeveryday/crawlers/config/.env
    networks:
      - blackeveryday_network
    restart: unless-stopped
    deploy:
      replicas: 2

networks:
  blackeveryday_network:
    external: true
