version: '3.8'

services:
  technolife-crawler:
    build: .
    env_file:
      - /opt/blackeveryday/config/.env.common
      - /opt/blackeveryday/crawlers/config/.env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    deploy:
      replicas: 20